### ISSUE TITLE
Does PicoKit work with current AFNetworking (2.5.4)

### ISSUE THREAD

**Issue by cnlier** [maxep/PicoKit#2]
My project uses the latest AFNetworking pod. However, PicoKit specifies AFNetworking 1.3.4. Does it also work with version 2.5.4?

**Comment by bagusflyer** [comment]
Have the same question.

**Comment by maxep** [comment]
Hi, sorry for the late response, I was on vacation.

Currently, it does not work with higher versions than 1.3.4. It needs a bit of rework to be compatible with AF 2.+
Don't know when I will have time to do so, hope soon. Otherwise, contributions are welcomes ;)

Regards,
