### ISSUE TITLE
got empty response

### ISSUE THREAD

**Issue by walkerwzy** [maxep/PicoKit#4]
I use`pod install` to run whole workspace, and all failed. 

```
Printing description of error:
Error Domain=com.leansoft.pico Code=-1000 
"Empty response" UserInfo=0x7fb0e96161a0 
{NSLocalizedDescription=Empty response}
```

and I run the original pico example projects, all good, so I think it might be the AFNetworking version issue, then remove the pod files and add the AF directory copied from examples manually, it worked.

**Comment by maxep** [comment]
I've recently updated PicoKit to use the last AFNetworking 2.5.4, this might fix this issue. But this update is not on cocoapod yet, to try it you can change your podfile to: 

```
pod 'PicoKit', :git => 'https://github.com/maxep/PicoKit.git'
```

**Comment by BrokenHomeStudiosLLC** [comment]
i tried ur fork but i am still seeing same issue, are you pointing to AFNetworking 2.6.3?

**Comment by BrokenHomeStudiosLLC** [comment]
you podspec says 2.6.0 for AFNetworking, and it is failing with empty response still, im attempting to add the AF source from example directly to project
